name: main
on:
  - push
  - pull_request
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: stable
        id: go
      - name: Code checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
        with:
          persist-credentials: false
      - name: Test
        run: |
          go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Publish coverage
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354  # v6.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage.txt
          fail_ci_if_error: false

