name: main
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
        id: go
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Publish coverage
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt

